### ISSUE TITLE
No Wrapper Installed after Clicking "Update" | Cannot create a new blank wrapper

### ISSUE THREAD

**Issue by Slin-89** [Gcenx/WineskinServer#368]
**Environment (please complete the following information):**
 - OS: 13.2
 - Winery version: 1.8.4
 - Master Wrapper version:
 - Engine version: WS^^WineCX64Bit21.2.0
 - Hardware: MacBook Pro 2020, 13inch, Intel
 - Application/Game Name: Couldnt install a game yet because of an issue

**Describe the bug**

After installing the Engine and updating the Wrapper. The "Create New Blank Wrapper" button is grayed out/ not clickable. Also in the Wrapper Version, it says "No Wrapper Installed" 

**To Reproduce**

I downloaded Wineskin. Moved .app to my application folder - > right-clicked -> open. Then I installed the engine and clicked "update" on the Wrapper Version (Wineskin-2.9.1.8). After Clicking ok the wrapper version still says "No Wrapper Installed". I cannot click "Create New Blank Wrapper"

**Expected behavior**
creating a new wrapper 

**LastRunWine.log**
Runtime Folder empty

**Comment by kubyon** [comment]
I'm pretty sure this is fixed the moment you posted this.

**Comment by Slin-89** [comment]
I tried reinstalling Wineskin, rebooting my mac and other engines. It downloads the wrapper, but in the wrapper folder is still empty and I still cannot create a new wrapper

**Comment by Gcenx** [comment]
> I tried reinstalling Wineskin, rebooting my mac and other engines. It downloads the wrapper, but in the wrapper folder is still empty and I still cannot create a new wrapper

Just clean out `/tmp` and run Winery and click “Update” button again and the wrapper should now download/install correctly.
